ALTER TABLE ZTCRM.Customer DROP CONSTRAINT CHK_CUSTOMER_TYPE;

ALTER TABLE ZTCRM.Customer ADD CONSTRAINT CHK_CUSTOMER_TYPE
    CHECK (CustomerType IN ('Individual', 'Corporate', 'Foreign'));

ALTER TABLE ZTCRM.Customer ADD PassportNo VARCHAR2(20);